### ISSUE TITLE
If kid doesn't have a story, still open individual page

### ISSUE THREAD

**Issue by cwhitten1** [zacmontague/DMApp#18]
EDIT: Still open individual page with placeholder in place of the story.

**Comment by cwhitten1** [comment]
I suggest you make a method boolean hasStory() in the Kids class to test this and handle stories there.

**Comment by zacmontague** [comment]
What should the placeholder say?

**Comment by cwhitten1** [comment]
Probably something like No Story Available At This Time or just No Story Available
